### ISSUE TITLE
Proposal for allowing file deletion

### ISSUE THREAD

**Issue by pameeela** [govCMS/GovCMS#231]
Currently, file deletion is not supported on SaaS, and temporary files are not deleted from the system. As a result, site owners have no method to remove files from their sites and have to create a ticket to request file deletion. This process is quite confusing for non-technical editors, and we field many enquiries about this topic. The situation is documented at https://www.govcms.support/support/solutions/articles/51000107026-why-aren-t-files-with-0-usage-being-removed-from-our-site-

I would like to propose an approach to managing file deletions within Drupal:
- Use the patch from https://www.drupal.org/project/drupal/issues/2949017#comment-13389865 to add the 'Delete any files' permissions
- Add VBO module: https://www.drupal.org/project/views_bulk_operations (this would be great regardless!)
- From here you can leave it up to site owners to configure, but our preferred setup is:
  - Create a view of temporary files accessible to users with the 'Delete any file' permission
  - Add the delete bulk operation to this view
  - Ensure the delete bulk operation is not available on the the main files view to prevent permanent files from being deleted

We have used this approach on many of our sites now without any issues and the patch has not needed a re-roll so far. I think this would be great to reduce the amount of overhead from the file deletion requests and queries.

**Comment by joshua-graham-adelphi** [comment]
+1

**Comment by klonos** [comment]
Hello @pameeela and thank for taking the time to start this discussion 👋🏼 

I could be wrong about this, but any delete VBO action does not delete the file, rather than mark it as temporary, relying on the default Drupal garbage collection to do the final actual deletion on cron run. Garbage collection in GovCMS has been disabled across SaaS though, until all the critical data-loss Drupal core issues are resolved (see https://www.drupal.org/node/2891902 and linked critical tickets still open).

This is the same problem as with the various contrib solutions like https://www.drupal.org/project/file_delete that we've considered (they mark the files as temporary, but they don't actually delete them - so they are of no use in this specific situation).

Having said that, Salsa has put forward a solution proposal last week, which is now pending decision/approval by Finance. Customers having to raise a ticket each time they want to delete files from the CMS is not an ideal workflow for them, and there are so many tickets raised to have files deleted which is creating a huge overhead in the GovCMS Service Desk. So rest assured, we are working on sorting this issue out for all of us as soon as possible.

**Comment by pameeela** [comment]
Hi Greg,

Thanks for replying.

Your assumption is incorrect. This method deletes the file. We only allow deletion of files that have been marked temporary as an added layer of protection against deleting files that are in use. The garbage collection process would eventually delete the temporary files (if it is enabled), but our clients want to delete the files immediately rather than waiting, which is why we came up with this approach. We are using it on many sites so I am quite sure of this.

I look forward to hearing the details of Salsa's proposal.

Cheers
Pam

**Comment by klonos** [comment]
Interesting @pameeela! I will try to make time and actually test your approach then, rather than making assumptions :) ...I'll have to set up a fresh instance of GovCMS, then apply the patch from https://www.drupal.org/project/drupal/issues/2949017#comment-13389865, and then also install VBO.

Gotta be sometime after the EoFY though, as the GovCMS Service Desk is really busy at the time.

Thanks once again 👍🏼

**Comment by joshua-graham-adelphi** [comment]
Doing my own testing.

I can confirm that files on the filesystem are deleted if the vbo module is triggered on file entities in GovCMS 9 stock (from composer).

If used on media entities, the file entities (and file in the filesystem) are left behind however.

Seeing as the request is for temporary file entities, they should in theory, not have a parent media entity, so the 2nd case is not an issue.

@see https://git.drupalcode.org/project/views_bulk_operations/-/blob/4.0.x/src/Plugin/Action/EntityDeleteAction.php#L32
` $entity->delete();`

**Comment by klonos** [comment]
Pinging @Ahmedjabar re the above ^^

**Comment by pameeela** [comment]
Thanks @joshua-graham-adelphi. Yes just to confirm, media items are not relevant here, they can be deleted the 'normal' way without any patches or special treatment.

But the issue is that deleting a media item leaves you with the orphaned file, so that's what this is trying to solve.

**Comment by pameeela** [comment]
Update here, with the release of https://www.drupal.org/project/media_file_delete my workaround, and the patch, are no longer needed.

I suggest adding this module instead.

**Comment by jibran** [comment]
Created https://github.com/govCMS/GovCMS/issues/314.

**Comment by thisisalistairsaccount** [comment]
See the update to #314 - we are currently reviewing internally

**Comment by silverham** [comment]
Adding a note that it very difficult to remove a file from search engines' indexes when the files is still publicly accessible. So another reason to consider allowing specific files to be deletable on demand.

**Comment by brett-sargeant** [comment]
just adding that this functionality would be very welcome.

**Comment by thisisalistairsaccount** [comment]
Hi All,

Media File Delete from #314 has been added to the GovCMS distribution as part of 2.16.0 - https://github.com/govCMS/GovCMS/releases/tag/2.16.0

Those running SaaS sites can request the module to be enabled via the GovCMS Service Desk.
