### ISSUE TITLE
Add reCAPTCHA v3 module to GovCMS

### ISSUE THREAD

**Issue by brett-sargeant** [govCMS/GovCMS#684]
[Copied from D8 Queue](https://github.com/govCMS/GovCMS8/issues/473)

What value does this module/package add to GovCMS?

reCAPTCHA v3 provides a better user experience by returning a score for each request without requiring the user to answer challenges.

Please provide a brief outline of what this module does.

"This module enables you to easily configure reCAPTCHA v3 and a fallback challenge (captcha/recaptcha v2 e.g). In case user fails reCAPTCHA v3, he can be prompted with an additional challenge to prove. This is an ideal way to maximize security without any user friction."

Who does this module benefit:

[X] end users
[ ] content editors
[ ] site builders
[ ] themers
[ ] developers

What is the maintenance and support status of the module. Describe the issue queue activity.
[8.x-1.7](https://www.drupal.org/project/recaptcha_v3/releases/8.x-1.7) Stable release covered by the Drupal Security Team released 11 October 2022
Works with Drupal: ^9.1 || ^10
issues appear to be getting fixed.

**Comment by thisisalistairsaccount** [comment]
Just to pad this out a bit more against the issue template:

** Module location:
https://www.drupal.org/project/recaptcha_v3

** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
This is an extension of existing functionality on offer within, but supports the updated methord of reCAPTCHA v3. It could be implemented at theme, but would make sense at the application layer to implement for all sites as captcha helps to filter users from bots.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
It does not. 

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
Setup in a similar fashion to the existing CAPTCHA and reCAPTCHA modules. Once enabled, the module is then available via modules like Webform rather than directly in the module.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

** Is the module designed to capture anonymous user data?
Sort of. It's designed to filter between bots and users. Depending on the interaction, it may capture data but not store it in the module or site itself

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
This would be used in places where forms are already in use. This should apply in the same manner as the other existing CAPTCHA modules and have the same impact.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
There are numerous issues in the queue that have been marked as Fixed and are actively being updated. The current module offering is Stable and supports the future state of Drupal 10, as well as the current D9. 

17,739 sites report using this module - https://www.drupal.org/project/usage/recaptcha_v3

** Additional information

**Comment by thisisalistairsaccount** [comment]
Noting the improvements to the user experience of CAPTCHA with this new version, and the option to fallback to older versions, this is being investigated by GovCMS for potential inclusion

**Comment by thisisalistairsaccount** [comment]
Hi all,

The reCAPTCHA v3 module has been added into release 3.13.0 https://github.com/govCMS/GovCMS/releases/tag/3.13.0 and is now available as part of the GovCMS distribution alongside the CAPTCHA and reCAPTCHA modules which work where fallback is required.

**Comment by thisisalistairsaccount** [comment]
Just reopening this one for now, we've had an issue with release 3.13.0 and will advise more on our GovTEAMS and Slack channels

**Comment by thisisalistairsaccount** [comment]
Noting we have made the call to continue with the 3.13.0 release, I'm closing this one as completed again :)
